version: "3.9"

services:
  db:
    image: postgres:14
    container_name: bonu_postgres_local
    restart: always
    environment:
      POSTGRES_USER: bonu_user
      POSTGRES_PASSWORD: bonu_pass
      POSTGRES_DB: bonu_cms
    ports:
      - "5434:5432"
    volumes:
      - bonu_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bonu_user -d bonu_cms"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  bonu_pgdata:
